source 'https://rubygems.org'

# QAT is a Cucumber-based toolkit for automating tests. (https://gitlab.readinessit.com:8083/qa-toolkit/qat-core)
gem 'qat', '~> 2.0', '>= 2.0.0'

# QAT-Web is a browser controller for Web testing (http://gitlab.readinessit.com:8083/qa-toolkit/qat-web)
#gem 'qat-web', '~> 2.0',  '>= 2.0.0'

# Ruby headless display interface (http://leonid.shevtsov.me/en/headless)
#gem 'headless', '~> 2.3', '>= 2.3.1'

# The next generation developer focused tool for automated testing of webapps (https://github.com/seleniumhq/selenium)
#gem 'selenium-webdriver', '~> 2.53', '>= 2.53.4'